import type { ActQuestStepDef } from '@/lib/game/acts/types'

export const ACT1_FINALE_SCENES = {
  witness: 'act1_witness_finale',
  heretic: 'act1_heretic_finale',
  hollow: 'act1_hollow_finale',
} as const

export const ACT1_QUEST_STEPS: ActQuestStepDef[] = [
  // ——— Свидетель ———
  {
    id: 'w_main_1',
    origin: 'witness',
    type: 'main',
    order: 1,
    titleHidden: '???',
    titleRevealed: 'Вернуться живым',
    hint: 'Камера отпускает только тех, кто помнит выход.',
    revealMessage: 'Сначала камера должна принять твой возврат — иначе учёт не начнётся.',
    completeMessage:
      'Ты вышел живым — камера приняла первый взгляд. Машина теперь знает: ты не одноразовый сосуд.',
    completeWhen: { kind: 'extractions', min: 1 },
    boostSceneId: 'act1_witness_reminder',
  },
  {
    id: 'w_main_2',
    origin: 'witness',
    type: 'main',
    order: 2,
    titleHidden: '???',
    titleRevealed: 'Тот, кто не дышит',
    hint: 'На дороге стоит телега без коня.',
    revealMessage: 'Бездыханный ведёт счёт даже свидетелям — найди телегу.',
    completeMessage:
      'Бездыханный запомнил тебя. Он торгует у края Синода — слухами дороже зубов.',
    completeWhen: { kind: 'flag', flag: 'met_breathless' },
    boostSceneId: 'act1_witness_merchant_oath',
    revealAfterStepId: 'w_main_1',
  },
  {
    id: 'w_main_3',
    origin: 'witness',
    type: 'main',
    order: 3,
    titleHidden: '???',
    titleRevealed: 'Частота колокола',
    hint: 'Колокол звенит не для всех.',
    revealMessage: 'В ту ночь Шествия колокол бил в последний раз — услышь частоту.',
    completeMessage:
      'Колокол принял твой пульс. Свидетель слышит то, что паломники унесли в трещину.',
    completeWhen: { kind: 'flag', flag: 'heard_the_bell' },
    boostSceneId: 'act1_witness_bell_covenant',
    revealAfterStepId: 'w_main_2',
  },
  {
    id: 'w_main_4',
    origin: 'witness',
    type: 'main',
    order: 4,
    titleHidden: '???',
    titleRevealed: 'Глубина памяти',
    hint: 'Свидетель должен дойти туда, где металл помнит имена.',
    revealMessage: 'Синод ведёт учёт на третьем ярусе — туда должен дойти свидетель.',
    completeMessage:
      'Камера запомнила глубину 3. Металл внизу хранит имена — ты близок к долгу.',
    completeWhen: { kind: 'best_depth', min: 3 },
    boostSceneId: 'act1_witness_synod_depth',
    revealAfterStepId: 'w_main_3',
  },
  {
    id: 'w_main_5',
    origin: 'witness',
    type: 'main',
    order: 5,
    titleHidden: '???',
    titleRevealed: 'Имя в металле',
    hint: 'Последняя запись ждёт у рта.',
    revealMessage: 'У Уст выгравировано имя того, кого ты видел — назови или запиши.',
    completeMessage:
      'Имя записано. Свидетель закрыл первый круг: мир больше не может притворяться, что ты не смотрел.',
    completeWhen: { kind: 'finale', sceneId: ACT1_FINALE_SCENES.witness },
    boostSceneId: ACT1_FINALE_SCENES.witness,
    revealAfterStepId: 'w_main_4',
  },
  {
    id: 'w_opt_depth',
    origin: 'witness',
    type: 'optional',
    order: 10,
    titleHidden: 'Глубже',
    titleRevealed: 'Четвёртый ярус',
    hint: 'Дойти до глубины 4 в одном спуске.',
    completeWhen: { kind: 'best_depth', min: 4 },
    revealAfterStepId: 'w_main_3',
  },
  {
    id: 'w_opt_synod',
    origin: 'witness',
    type: 'optional',
    order: 11,
    titleHidden: 'Синод',
    titleRevealed: 'Запись Синода',
    hint: 'Встретить аколита и занести в журнал.',
    completeWhen: { kind: 'journal', entryId: 'npc_synod' },
    revealAfterStepId: 'w_main_3',
  },
  {
    id: 'w_opt_twice',
    origin: 'witness',
    type: 'optional',
    order: 12,
    titleHidden: 'Дважды',
    titleRevealed: 'Дважды живым',
    hint: 'Выйти из спуска живым два раза.',
    completeWhen: { kind: 'extractions', min: 2 },
    revealAfterStepId: 'w_main_1',
  },

  // ——— Еретик ———
  {
    id: 'h_main_1',
    origin: 'heretic',
    type: 'main',
    order: 1,
    titleHidden: '???',
    titleRevealed: 'Первый ответ',
    hint: 'Машина задаёт вопрос только тем, кто вернулся.',
    completeWhen: { kind: 'extractions', min: 1 },
    boostSceneId: 'act1_heretic_machine_echo',
  },
  {
    id: 'h_main_2',
    origin: 'heretic',
    type: 'main',
    order: 2,
    titleHidden: '???',
    titleRevealed: 'Торговец без дыхания',
    hint: 'Бездыханный знает цену вопроса.',
    completeWhen: { kind: 'flag', flag: 'met_breathless' },
    boostSceneId: 'act1_heretic_merchant_price',
    revealAfterStepId: 'h_main_1',
  },
  {
    id: 'h_main_3',
    origin: 'heretic',
    type: 'main',
    order: 3,
    titleHidden: '???',
    titleRevealed: 'Надписи на стене',
    hint: 'Прочитать то, что Синод стирает.',
    completeWhen: { kind: 'flag', flag: 'read_the_writings' },
    boostSceneId: 'act1_heretic_writing_wall',
    revealAfterStepId: 'h_main_2',
  },
  {
    id: 'h_main_4',
    origin: 'heretic',
    type: 'main',
    order: 4,
    titleHidden: '???',
    titleRevealed: 'Шестерня и клятва',
    hint: 'Ответить тому, кто крутится вне закона.',
    completeWhen: { kind: 'flag', flag: 'heretic_answered' },
    boostSceneId: 'act1_heretic_cog_pact',
    revealAfterStepId: 'h_main_3',
  },
  {
    id: 'h_main_5',
    origin: 'heretic',
    type: 'main',
    order: 5,
    titleHidden: '???',
    titleRevealed: 'Вопрос без Синода',
    hint: 'Финал у рта — не исповедь, а формула.',
    completeWhen: { kind: 'finale', sceneId: ACT1_FINALE_SCENES.heretic },
    boostSceneId: ACT1_FINALE_SCENES.heretic,
    revealAfterStepId: 'h_main_4',
  },
  {
    id: 'h_opt_cog',
    origin: 'heretic',
    type: 'optional',
    order: 10,
    titleHidden: 'Шестерня',
    titleRevealed: 'Встреча с шестерней',
    hint: 'Найти еретическую шестерню в глубине.',
    completeWhen: { kind: 'flag', flag: 'met_heretic_cog' },
    revealAfterStepId: 'h_main_2',
  },
  {
    id: 'h_opt_depth',
    origin: 'heretic',
    type: 'optional',
    order: 11,
    titleHidden: 'Глубина',
    titleRevealed: 'Третий ярус',
    hint: 'Дойти до глубины 3.',
    completeWhen: { kind: 'best_depth', min: 3 },
    revealAfterStepId: 'h_main_3',
  },
  {
    id: 'h_opt_twice',
    origin: 'heretic',
    type: 'optional',
    order: 12,
    titleHidden: 'Дважды',
    titleRevealed: 'Дважды живым',
    hint: 'Два успешных извлечения.',
    completeWhen: { kind: 'extractions', min: 2 },
    revealAfterStepId: 'h_main_1',
  },

  // ——— Полый ———
  {
    id: 'o_main_1',
    origin: 'hollow',
    type: 'main',
    order: 1,
    titleHidden: '???',
    titleRevealed: 'Пустая форма',
    hint: 'Вернуться, чтобы камера узнала силуэт.',
    completeWhen: { kind: 'extractions', min: 1 },
    boostSceneId: 'act1_hollow_empty_chapel',
  },
  {
    id: 'o_main_2',
    origin: 'hollow',
    type: 'main',
    order: 2,
    titleHidden: '???',
    titleRevealed: 'Долг без имени',
    hint: 'Бездыханный ведёт счёт даже пустым.',
    completeWhen: { kind: 'flag', flag: 'met_breathless' },
    boostSceneId: 'act1_hollow_merchant_debt',
    revealAfterStepId: 'o_main_1',
  },
  {
    id: 'o_main_3',
    origin: 'hollow',
    type: 'main',
    order: 3,
    titleHidden: '???',
    titleRevealed: 'Маска в руке',
    hint: 'Взять то, что скрывает отсутствие лица.',
    completeWhen: { kind: 'flag', flag: 'claimed_mask' },
    boostSceneId: 'act1_hollow_mask_rite',
    revealAfterStepId: 'o_main_2',
  },
  {
    id: 'o_main_4',
    origin: 'hollow',
    type: 'main',
    order: 4,
    titleHidden: '???',
    titleRevealed: 'Принять обвал',
    hint: 'Упасть и вернуться — не сбой, а урок.',
    completeWhen: { kind: 'flag', flag: 'experienced_failure' },
    boostSceneId: 'act1_hollow_collapse_lesson',
    revealAfterStepId: 'o_main_3',
  },
  {
    id: 'o_main_5',
    origin: 'hollow',
    type: 'main',
    order: 5,
    titleHidden: '???',
    titleRevealed: 'Имя, которого нет',
    hint: 'Финал: камера спрашивает то, чего у тебя нет.',
    completeWhen: { kind: 'finale', sceneId: ACT1_FINALE_SCENES.hollow },
    boostSceneId: ACT1_FINALE_SCENES.hollow,
    revealAfterStepId: 'o_main_4',
  },
  {
    id: 'o_opt_bell',
    origin: 'hollow',
    type: 'optional',
    order: 10,
    titleHidden: 'Колокол',
    titleRevealed: 'Звон без эха',
    hint: 'Услышать колокол.',
    completeWhen: { kind: 'flag', flag: 'heard_the_bell' },
    revealAfterStepId: 'o_main_2',
  },
  {
    id: 'o_opt_wax',
    origin: 'hollow',
    type: 'optional',
    order: 11,
    titleHidden: 'Воск',
    titleRevealed: 'Восковой паломник',
    hint: 'Встретить воскового и записать в журнал.',
    completeWhen: { kind: 'journal', entryId: 'npc_wax' },
    revealAfterStepId: 'o_main_2',
  },
  {
    id: 'o_opt_twice',
    origin: 'hollow',
    type: 'optional',
    order: 12,
    titleHidden: 'Дважды',
    titleRevealed: 'Дважды живым',
    hint: 'Два извлечения.',
    completeWhen: { kind: 'extractions', min: 2 },
    revealAfterStepId: 'o_main_1',
  },
]

export function stepsForOrigin(origin: string): ActQuestStepDef[] {
  return ACT1_QUEST_STEPS.filter((s) => s.origin === origin).sort(
    (a, b) => a.order - b.order,
  )
}
