import type { ActQuestStepDef } from '@/lib/game/acts/types'

export const ACT1_FINALE_SCENES = {
  witness: 'act1_witness_finale',
  heretic: 'act1_heretic_finale',
  hollow: 'act1_hollow_finale',
} as const

export const ACT1_QUEST_STEPS: ActQuestStepDef[] = [
  // ——— Свидетель ———
  {
    id: 'w_main_1',
    origin: 'witness',
    type: 'main',
    order: 1,
    titleHidden: '???',
    titleRevealed: 'Вернуться живым',
    hint: 'Камера отпускает только тех, кто помнит выход.',
    revealMessage:
      'Сначала камера должна принять твой возврат — иначе учёт не начнётся.',
    completeMessage:
      'Ты вышел живым. Дорога на обочине Шествия узнала твой шаг — Машина записала первый взгляд.',
    completeWhen: { kind: 'scene', sceneId: 'act1_witness_reminder' },
    boostSceneId: 'act1_witness_reminder',
    scenePrerequisites: [{ kind: 'extractions', min: 1 }],
    reward: { echo: 1 },
  },
  {
    id: 'w_main_2',
    origin: 'witness',
    type: 'main',
    order: 2,
    titleHidden: '???',
    titleRevealed: 'Тот, кто не дышит',
    hint: 'На дороге стоит телега без коня.',
    revealMessage: 'Бездыханный ведёт счёт даже свидетелям — найди телегу.',
    completeMessage:
      'Бездыханный запомнил тебя. Он торгует у края Синода — слухами дороже зубов.',
    completeWhen: { kind: 'scene', sceneId: 'act1_witness_merchant_oath' },
    boostSceneId: 'act1_witness_merchant_oath',
    revealAfterStepId: 'w_main_1',
    reward: { materials: { wax_seal: 1 } },
  },
  {
    id: 'w_main_3',
    origin: 'witness',
    type: 'main',
    order: 3,
    titleHidden: '???',
    titleRevealed: 'Частота колокола',
    hint: 'Колокол звенит не для всех.',
    revealMessage: 'В ту ночь Шествия колокол бил в последний раз — услышь частоту.',
    completeMessage:
      'Колокол принял твой пульс. Свидетель слышит то, что паломники унесли в трещину.',
    completeWhen: { kind: 'scene', sceneId: 'act1_witness_bell_covenant' },
    boostSceneId: 'act1_witness_bell_covenant',
    revealAfterStepId: 'w_main_2',
    reward: { materials: { choir_splinter: 1 }, echo: 1 },
  },
  {
    id: 'w_main_4',
    origin: 'witness',
    type: 'main',
    order: 4,
    titleHidden: '???',
    titleRevealed: 'Глубина памяти',
    hint: 'Свидетель должен дойти туда, где металл помнит имена.',
    revealMessage: 'Синод ведёт учёт на третьем ярусе — туда должен дойти свидетель.',
    completeMessage:
      'Камера запомнила глубину 3. Металл внизу хранит имена — ты близок к долгу.',
    completeWhen: {
      kind: 'all',
      conditions: [
        { kind: 'scene', sceneId: 'act1_witness_synod_depth' },
        { kind: 'best_depth', min: 3 },
      ],
    },
    boostSceneId: 'act1_witness_synod_depth',
    scenePrerequisites: [{ kind: 'best_depth', min: 3 }],
    revealAfterStepId: 'w_main_3',
    reward: { materials: { iron_shard: 2 }, echo: 2 },
  },
  {
    id: 'w_main_5',
    origin: 'witness',
    type: 'main',
    order: 5,
    titleHidden: '???',
    titleRevealed: 'Имя в металле',
    hint: 'Последняя запись ждёт у рта.',
    revealMessage: 'У Уст выгравировано имя того, кого ты видел — назови или запиши.',
    completeMessage:
      'Имя записано. Свидетель закрыл первый круг: мир больше не может притворяться, что ты не смотрел.',
    completeWhen: { kind: 'finale', sceneId: ACT1_FINALE_SCENES.witness },
    boostSceneId: ACT1_FINALE_SCENES.witness,
    revealAfterStepId: 'w_main_4',
    reward: { echo: 5, journalEntries: ['act1_witness'] },
  },
  {
    id: 'w_opt_depth',
    origin: 'witness',
    type: 'optional',
    order: 10,
    titleHidden: 'Глубже',
    titleRevealed: 'Четвёртый ярус',
    hint: 'Дойти до глубины 4 и найти писца Синода.',
    revealMessage: 'На четвёртом ярусе Синод ведёт учёт тем, кто ещё дышит.',
    completeMessage:
      'Писец записал твой шаг на четвёртом ярусе. Синод теперь знает: свидетель не остановился на третьем счёте.',
    completeWhen: { kind: 'scene', sceneId: 'act1_witness_opt_depth' },
    boostSceneId: 'act1_witness_opt_depth',
    scenePrerequisites: [{ kind: 'best_depth', min: 4 }],
    revealAfterStepId: 'w_main_3',
    reward: { echo: 3, journalEntries: ['act1_opt_depth'] },
  },
  {
    id: 'w_opt_synod',
    origin: 'witness',
    type: 'optional',
    order: 11,
    titleHidden: 'Синод',
    titleRevealed: 'Запись Синода',
    hint: 'Встретить писца и занести метку в журнал.',
    revealMessage: 'Адепт ждёт у стены — не для казни, для учёта.',
    completeMessage:
      'Метка Синода на запястье — не кандалы. Это подпись под тем, что ты уже видел.',
    completeWhen: { kind: 'scene', sceneId: 'act1_witness_opt_synod' },
    boostSceneId: 'act1_witness_opt_synod',
    revealAfterStepId: 'w_main_3',
    reward: { materials: { wax_seal: 2 }, flags: ['synod_mark'] },
  },
  {
    id: 'w_opt_twice',
    origin: 'witness',
    type: 'optional',
    order: 12,
    titleHidden: 'Дважды',
    titleRevealed: 'Дважды живым',
    hint: 'Выйти из спуска живым два раза и услышать хрониста.',
    revealMessage: 'Камера помнит двойной возврат — это редкость даже для сосудов.',
    completeMessage:
      'Два живых круга. Хронист камеры вырезал на стене твой силуэт — второй раз чётче первого.',
    completeWhen: { kind: 'scene', sceneId: 'act1_witness_opt_twice' },
    boostSceneId: 'act1_witness_opt_twice',
    scenePrerequisites: [{ kind: 'extractions', min: 2 }],
    revealAfterStepId: 'w_main_1',
    reward: { echo: 4 },
  },

  // ——— Еретик ———
  {
    id: 'h_main_1',
    origin: 'heretic',
    type: 'main',
    order: 1,
    titleHidden: '???',
    titleRevealed: 'Первый ответ',
    hint: 'Машина задаёт вопрос только тем, кто вернулся.',
    revealMessage: 'Камера ещё хранит тепло возврата — Машина ждёт первый ответ без Синода.',
    completeMessage:
      'Вопрос задан. Голос под дорогой услышал — еретик больше не молчит в учёте.',
    completeWhen: { kind: 'scene', sceneId: 'act1_heretic_machine_echo' },
    boostSceneId: 'act1_heretic_machine_echo',
    scenePrerequisites: [{ kind: 'extractions', min: 1 }],
    reward: { echo: 1 },
  },
  {
    id: 'h_main_2',
    origin: 'heretic',
    type: 'main',
    order: 2,
    titleHidden: '???',
    titleRevealed: 'Торговец без дыхания',
    hint: 'Бездыханный знает цену вопроса.',
    revealMessage: 'Телега без коня — счёт, который еретик должен оплатить формулой.',
    completeMessage:
      'Бездыханный записал цену. Синод будет спорить с его почерком — тебе это на руку.',
    completeWhen: { kind: 'scene', sceneId: 'act1_heretic_merchant_price' },
    boostSceneId: 'act1_heretic_merchant_price',
    revealAfterStepId: 'h_main_1',
    reward: { materials: { wax_seal: 1 } },
  },
  {
    id: 'h_main_3',
    origin: 'heretic',
    type: 'main',
    order: 3,
    titleHidden: '???',
    titleRevealed: 'Надписи на стене',
    hint: 'Прочитать то, что Синод стирает.',
    revealMessage: 'Стена в катакомбах обновляется каждую ночь — прочитай до стирания.',
    completeMessage:
      'Формулы дыхания записаны в память. Синод назовёт это язвой — ты назовёшь учебником.',
    completeWhen: { kind: 'scene', sceneId: 'act1_heretic_writing_wall' },
    boostSceneId: 'act1_heretic_writing_wall',
    revealAfterStepId: 'h_main_2',
    reward: { materials: { folio_page: 1 }, echo: 1 },
  },
  {
    id: 'h_main_4',
    origin: 'heretic',
    type: 'main',
    order: 4,
    titleHidden: '???',
    titleRevealed: 'Шестерня и клятва',
    hint: 'Ответить тому, кто крутится вне закона.',
    revealMessage: 'Шестерня без оси ждёт точности — не молитвы.',
    completeMessage:
      'Пакт с шестерней заключён. Машина приняла пульс напрямую — Синод отстаёт на один вдох.',
    completeWhen: { kind: 'scene', sceneId: 'act1_heretic_cog_pact' },
    boostSceneId: 'act1_heretic_cog_pact',
    revealAfterStepId: 'h_main_3',
    reward: { materials: { iron_shard: 2 }, flags: ['heretic_answered'] },
  },
  {
    id: 'h_main_5',
    origin: 'heretic',
    type: 'main',
    order: 5,
    titleHidden: '???',
    titleRevealed: 'Вопрос без Синода',
    hint: 'Финал у рта — не исповедь, а формула.',
    revealMessage: 'У Уст воздух густой от невысказанных исповедей — произнеси формулу.',
    completeMessage:
      'Формула принята. Первый акт еретика закрыт — Синод ответит силой, не словом.',
    completeWhen: { kind: 'finale', sceneId: ACT1_FINALE_SCENES.heretic },
    boostSceneId: ACT1_FINALE_SCENES.heretic,
    revealAfterStepId: 'h_main_4',
    reward: { echo: 5, journalEntries: ['act1_heretic'] },
  },
  {
    id: 'h_opt_cog',
    origin: 'heretic',
    type: 'optional',
    order: 10,
    titleHidden: 'Шестерня',
    titleRevealed: 'Встреча с шестерней',
    hint: 'Найти еретическую шестерню в глубине.',
    revealMessage: 'Железо без оси крутится в воздухе — вопрос без ответа Синода.',
    completeMessage:
      'Шестерня запомнила твой голос. У Порога Распада откроется иной путь.',
    completeWhen: { kind: 'scene', sceneId: 'act1_heretic_opt_cog' },
    boostSceneId: 'act1_heretic_opt_cog',
    revealAfterStepId: 'h_main_2',
    reward: { flags: ['met_heretic_cog'], journalEntries: ['npc_heretic'] },
  },
  {
    id: 'h_opt_depth',
    origin: 'heretic',
    type: 'optional',
    order: 11,
    titleHidden: 'Глубина',
    titleRevealed: 'Третий ярус',
    hint: 'Дойти до глубины 3 и услышать эхо формулы.',
    revealMessage: 'На третьем ярусе формулы звучат громче молитв.',
    completeMessage:
      'Глубина 3 принята. Стены помнят твой вопрос — не твоё имя.',
    completeWhen: { kind: 'scene', sceneId: 'act1_heretic_opt_depth' },
    boostSceneId: 'act1_heretic_opt_depth',
    scenePrerequisites: [{ kind: 'best_depth', min: 3 }],
    revealAfterStepId: 'h_main_3',
    reward: { echo: 3, materials: { iron_shard: 1 } },
  },
  {
    id: 'h_opt_twice',
    origin: 'heretic',
    type: 'optional',
    order: 12,
    titleHidden: 'Дважды',
    titleRevealed: 'Дважды живым',
    hint: 'Два успешных извлечения — хронист запишет.',
    revealMessage: 'Двойной возврат — редкая валюта у Машины.',
    completeMessage:
      'Два живых круга. Машина вычла из петли два вдоха — тебе оставила эхо.',
    completeWhen: { kind: 'scene', sceneId: 'act1_heretic_opt_twice' },
    boostSceneId: 'act1_heretic_opt_twice',
    scenePrerequisites: [{ kind: 'extractions', min: 2 }],
    revealAfterStepId: 'h_main_1',
    reward: { echo: 4 },
  },

  // ——— Пустой ———
  {
    id: 'o_main_1',
    origin: 'hollow',
    type: 'main',
    order: 1,
    titleHidden: '???',
    titleRevealed: 'Пустая форма',
    hint: 'Вернуться, чтобы камера узнала силуэт.',
    revealMessage:
      'Камера отпустила тебя — теперь она должна узнать форму, которой нет имени.',
    completeMessage:
      'Часовня без лиц приняла твой силуэт. Пустота здесь — не проклятие, а признание.',
    completeWhen: { kind: 'scene', sceneId: 'act1_hollow_empty_chapel' },
    boostSceneId: 'act1_hollow_empty_chapel',
    scenePrerequisites: [{ kind: 'extractions', min: 1 }],
    reward: { echo: 1 },
  },
  {
    id: 'o_main_2',
    origin: 'hollow',
    type: 'main',
    order: 2,
    titleHidden: '???',
    titleRevealed: 'Долг без имени',
    hint: 'Бездыханный ведёт счёт даже пустым.',
    revealMessage: 'У пустых тоже есть долг — минус одно имя, плюс одна маска.',
    completeMessage:
      'Бездыханный записал пустоту в счёт. Синод любит, когда отсутствие хоть чем-то звенит.',
    completeWhen: { kind: 'scene', sceneId: 'act1_hollow_merchant_debt' },
    boostSceneId: 'act1_hollow_merchant_debt',
    revealAfterStepId: 'o_main_1',
    reward: { materials: { wax_seal: 1 } },
  },
  {
    id: 'o_main_3',
    origin: 'hollow',
    type: 'main',
    order: 3,
    titleHidden: '???',
    titleRevealed: 'Маска в руке',
    hint: 'Взять то, что скрывает отсутствие лица.',
    revealMessage: 'Маска тяжелее пустой керамики — обряд без лица ждёт.',
    completeMessage:
      'Маска на поясе. Тело и отсутствие наконец совпали — голод под доспехами стих.',
    completeWhen: { kind: 'scene', sceneId: 'act1_hollow_mask_rite' },
    boostSceneId: 'act1_hollow_mask_rite',
    revealAfterStepId: 'o_main_2',
    reward: { materials: { choir_splinter: 1 }, flags: ['claimed_mask'] },
  },
  {
    id: 'o_main_4',
    origin: 'hollow',
    type: 'main',
    order: 4,
    titleHidden: '???',
    titleRevealed: 'Принять обвал',
    hint: 'Упасть и вернуться — не сбой, а урок.',
    revealMessage:
      'Камера помнит падение. Пустота не спасает от гравитации долга — прими урок.',
    completeMessage:
      'Обвал принят. Машина вытянула сосуд и оставила пятно — теперь это карта, не клеймо.',
    completeWhen: { kind: 'scene', sceneId: 'act1_hollow_collapse_lesson' },
    boostSceneId: 'act1_hollow_collapse_lesson',
    scenePrerequisites: [{ kind: 'flag', flag: 'experienced_failure' }],
    revealAfterStepId: 'o_main_3',
    reward: { echo: 3 },
  },
  {
    id: 'o_main_5',
    origin: 'hollow',
    type: 'main',
    order: 5,
    titleHidden: '???',
    titleRevealed: 'Имя, которого нет',
    hint: 'Финал: камера спрашивает то, чего у тебя нет.',
    revealMessage: 'У Рта спрашивают имя — у тебя есть только честная пустота.',
    completeMessage:
      'Записано: отсутствие. Первый акт пустого закрыт — камера знает форму без имени.',
    completeWhen: { kind: 'finale', sceneId: ACT1_FINALE_SCENES.hollow },
    boostSceneId: ACT1_FINALE_SCENES.hollow,
    revealAfterStepId: 'o_main_4',
    reward: { echo: 5, journalEntries: ['act1_hollow'] },
  },
  {
    id: 'o_opt_bell',
    origin: 'hollow',
    type: 'optional',
    order: 10,
    titleHidden: 'Колокол',
    titleRevealed: 'Звон без эха',
    hint: 'Услышать колокол у старца пустоты.',
    revealMessage: 'Колокол бьёт — но эха нет. Только пустой ветер отвечает.',
    completeMessage:
      'Звон прошёл сквозь тебя, не зацепившись. Старец пустоты кивнул: «Так и должно быть.»',
    completeWhen: { kind: 'scene', sceneId: 'act1_hollow_opt_bell' },
    boostSceneId: 'act1_hollow_opt_bell',
    revealAfterStepId: 'o_main_2',
    reward: { flags: ['heard_the_bell'], journalEntries: ['act1_opt_bell'] },
  },
  {
    id: 'o_opt_wax',
    origin: 'hollow',
    type: 'optional',
    order: 11,
    titleHidden: 'Воск',
    titleRevealed: 'Восковой паломник',
    hint: 'Встретить воскового — пустота считается иначе.',
    revealMessage: 'Паломник досчитывает пульс. У пустого его нет — только ритм камеры.',
    completeMessage:
      'Восковой записал пустоту как «ноль». Журнал принял — лица без пульса тоже существуют.',
    completeWhen: { kind: 'scene', sceneId: 'act1_hollow_opt_wax' },
    boostSceneId: 'act1_hollow_opt_wax',
    revealAfterStepId: 'o_main_2',
    reward: { materials: { wax_seal: 2 }, journalEntries: ['npc_wax'] },
  },
  {
    id: 'o_opt_twice',
    origin: 'hollow',
    type: 'optional',
    order: 12,
    titleHidden: 'Дважды',
    titleRevealed: 'Дважды живым',
    hint: 'Два извлечения — хронист вырежет второй силуэт.',
    revealMessage: 'Два возврата без имени — редкость. Камера вырежет силуэт глубже.',
    completeMessage:
      'Второй силуэт на стене чётче первого. Пустота дважды доказала, что форма держится.',
    completeWhen: { kind: 'scene', sceneId: 'act1_hollow_opt_twice' },
    boostSceneId: 'act1_hollow_opt_twice',
    scenePrerequisites: [{ kind: 'extractions', min: 2 }],
    revealAfterStepId: 'o_main_1',
    reward: { echo: 4 },
  },
]

export function stepsForOrigin(origin: string): ActQuestStepDef[] {
  return ACT1_QUEST_STEPS.filter((s) => s.origin === origin).sort(
    (a, b) => a.order - b.order,
  )
}
