import type { ActQuestStepDef } from '@/lib/game/acts/types'

export const ACT1_FINALE_SCENES = {
  witness: 'act1_witness_finale',
  heretic: 'act1_heretic_finale',
  hollow: 'act1_hollow_finale',
} as const

export const ACT1_QUEST_STEPS: ActQuestStepDef[] = [
  // ——— Свидетель ———
  {
    id: 'w_main_1',
    origin: 'witness',
    type: 'main',
    order: 1,
    titleHidden: '???',
    titleRevealed: 'Вернуться живым',
    hint: 'Камера отпускает только тех, кто помнит выход.',
    revealMessage:
      'Сначала камера должна принять твой возврат — иначе учёт не начнётся.',
    completeMessage:
      'Ты вышел живым. Дорога на обочине Шествия узнала твой шаг — Машина записала первый взгляд.',
    completeWhen: { kind: 'scene', sceneId: 'act1_witness_reminder' },
    boostSceneId: 'act1_witness_reminder',
    scenePrerequisites: [{ kind: 'extractions', min: 1 }],
    reward: { echo: 1 },
  },
  {
    id: 'w_main_2',
    origin: 'witness',
    type: 'main',
    order: 2,
    titleHidden: '???',
    titleRevealed: 'Тот, кто не дышит',
    hint: 'На дороге стоит телега без коня.',
    revealMessage: 'Бездыханный ведёт счёт даже свидетелям — найди телегу.',
    completeMessage:
      'Бездыханный запомнил тебя. Он торгует у края Синода — слухами дороже зубов.',
    completeWhen: { kind: 'scene', sceneId: 'act1_witness_merchant_oath' },
    boostSceneId: 'act1_witness_merchant_oath',
    revealAfterStepId: 'w_main_1',
    reward: { materials: { wax_seal: 1 } },
  },
  {
    id: 'w_main_3',
    origin: 'witness',
    type: 'main',
    order: 3,
    titleHidden: '???',
    titleRevealed: 'Частота колокола',
    hint: 'Колокол звенит не для всех.',
    revealMessage: 'В ту ночь Шествия колокол бил в последний раз — услышь частоту.',
    completeMessage:
      'Колокол принял твой пульс. Свидетель слышит то, что паломники унесли в трещину.',
    completeWhen: { kind: 'scene', sceneId: 'act1_witness_bell_covenant' },
    boostSceneId: 'act1_witness_bell_covenant',
    revealAfterStepId: 'w_main_2',
    reward: { materials: { choir_splinter: 1 }, echo: 1 },
  },
  {
    id: 'w_main_4',
    origin: 'witness',
    type: 'main',
    order: 4,
    titleHidden: '???',
    titleRevealed: 'Глубина памяти',
    hint: 'Свидетель должен дойти туда, где металл помнит имена.',
    revealMessage: 'Синод ведёт учёт на третьем ярусе — туда должен дойти свидетель.',
    completeMessage:
      'Камера запомнила глубину 3. Металл внизу хранит имена — ты близок к долгу.',
    completeWhen: {
      kind: 'all',
      conditions: [
        { kind: 'scene', sceneId: 'act1_witness_synod_depth' },
        { kind: 'best_depth', min: 3 },
      ],
    },
    boostSceneId: 'act1_witness_synod_depth',
    scenePrerequisites: [{ kind: 'best_depth', min: 3 }],
    revealAfterStepId: 'w_main_3',
    reward: { materials: { iron_shard: 2 }, echo: 2 },
  },
  {
    id: 'w_main_5',
    origin: 'witness',
    type: 'main',
    order: 5,
    titleHidden: '???',
    titleRevealed: 'Имя в металле',
    hint: 'Последняя запись ждёт у рта.',
    revealMessage: 'У Уст выгравировано имя того, кого ты видел — назови или запиши.',
    completeMessage:
      'Имя записано. Свидетель закрыл первый круг: мир больше не может притворяться, что ты не смотрел.',
    completeWhen: { kind: 'finale', sceneId: ACT1_FINALE_SCENES.witness },
    boostSceneId: ACT1_FINALE_SCENES.witness,
    revealAfterStepId: 'w_main_4',
    reward: { echo: 5, journalEntries: ['act1_witness'] },
  },
  {
    id: 'w_opt_depth',
    origin: 'witness',
    type: 'optional',
    order: 10,
    titleHidden: 'Глубже',
    titleRevealed: 'Четвёртый ярус',
    hint: 'Дойти до глубины 4 и найти писца Синода.',
    revealMessage: 'На четвёртом ярусе Синод ведёт учёт тем, кто ещё дышит.',
    completeMessage:
      'Писец записал твой шаг на четвёртом ярусе. Синод теперь знает: свидетель не остановился на третьем счёте.',
    completeWhen: { kind: 'scene', sceneId: 'act1_witness_opt_depth' },
    boostSceneId: 'act1_witness_opt_depth',
    scenePrerequisites: [{ kind: 'best_depth', min: 4 }],
    revealAfterStepId: 'w_main_3',
    reward: { echo: 3, journalEntries: ['act1_opt_depth'] },
  },
  {
    id: 'w_opt_synod',
    origin: 'witness',
    type: 'optional',
    order: 11,
    titleHidden: 'Синод',
    titleRevealed: 'Запись Синода',
    hint: 'Встретить писца и занести метку в журнал.',
    revealMessage: 'Адепт ждёт у стены — не для казни, для учёта.',
    completeMessage:
      'Метка Синода на запястье — не кандалы. Это подпись под тем, что ты уже видел.',
    completeWhen: { kind: 'scene', sceneId: 'act1_witness_opt_synod' },
    boostSceneId: 'act1_witness_opt_synod',
    revealAfterStepId: 'w_main_3',
    reward: { materials: { wax_seal: 2 }, flags: ['synod_mark'] },
  },
  {
    id: 'w_opt_twice',
    origin: 'witness',
    type: 'optional',
    order: 12,
    titleHidden: 'Дважды',
    titleRevealed: 'Дважды живым',
    hint: 'Выйти из спуска живым два раза и услышать хрониста.',
    revealMessage: 'Камера помнит двойной возврат — это редкость даже для сосудов.',
    completeMessage:
      'Два живых круга. Хронист камеры вырезал на стене твой силуэт — второй раз чётче первого.',
    completeWhen: { kind: 'scene', sceneId: 'act1_witness_opt_twice' },
    boostSceneId: 'act1_witness_opt_twice',
    scenePrerequisites: [{ kind: 'extractions', min: 2 }],
    revealAfterStepId: 'w_main_1',
    reward: { echo: 4 },
  },

  // ——— Еретик ———
  {
    id: 'h_main_1',
    origin: 'heretic',
    type: 'main',
    order: 1,
    titleHidden: '???',
    titleRevealed: 'Первый ответ',
    hint: 'Машина задаёт вопрос только тем, кто вернулся.',
    revealMessage: 'Камера ещё хранит тепло возврата — Машина ждёт первый ответ без Синода.',
    completeMessage:
      'Вопрос задан. Голос под дорогой услышал — еретик больше не молчит в учёте.',
    completeWhen: { kind: 'scene', sceneId: 'act1_heretic_machine_echo' },
    boostSceneId: 'act1_heretic_machine_echo',
    scenePrerequisites: [{ kind: 'extractions', min: 1 }],
    reward: { echo: 1 },
  },
  {
    id: 'h_main_2',
    origin: 'heretic',
    type: 'main',
    order: 2,
    titleHidden: '???',
    titleRevealed: 'Торговец без дыхания',
    hint: 'Бездыханный знает цену вопроса.',
    revealMessage: 'Телега без коня — счёт, который еретик должен оплатить формулой.',
    completeMessage:
      'Бездыханный записал цену. Синод будет спорить с его почерком — тебе это на руку.',
    completeWhen: { kind: 'scene', sceneId: 'act1_heretic_merchant_price' },
    boostSceneId: 'act1_heretic_merchant_price',
    revealAfterStepId: 'h_main_1',
    reward: { materials: { wax_seal: 1 } },
  },
  {
    id: 'h_main_3',
    origin: 'heretic',
    type: 'main',
    order: 3,
    titleHidden: '???',
    titleRevealed: 'Надписи на стене',
    hint: 'Прочитать то, что Синод стирает.',
    revealMessage: 'Стена в катакомбах обновляется каждую ночь — прочитай до стирания.',
    completeMessage:
      'Формулы дыхания записаны в память. Синод назовёт это язвой — ты назовёшь учебником.',
    completeWhen: { kind: 'scene', sceneId: 'act1_heretic_writing_wall' },
    boostSceneId: 'act1_heretic_writing_wall',
    revealAfterStepId: 'h_main_2',
    reward: { materials: { folio_page: 1 }, echo: 1 },
  },
  {
    id: 'h_main_4',
    origin: 'heretic',
    type: 'main',
    order: 4,
    titleHidden: '???',
    titleRevealed: 'Шестерня и клятва',
    hint: 'Ответить тому, кто крутится вне закона.',
    revealMessage: 'Шестерня без оси ждёт точности — не молитвы.',
    completeMessage:
      'Пакт с шестерней заключён. Машина приняла пульс напрямую — Синод отстаёт на один вдох.',
    completeWhen: { kind: 'scene', sceneId: 'act1_heretic_cog_pact' },
    boostSceneId: 'act1_heretic_cog_pact',
    revealAfterStepId: 'h_main_3',
    reward: { materials: { iron_shard: 2 }, flags: ['heretic_answered'] },
  },
  {
    id: 'h_main_5',
    origin: 'heretic',
    type: 'main',
    order: 5,
    titleHidden: '???',
    titleRevealed: 'Вопрос без Синода',
    hint: 'Финал у рта — не исповедь, а формула.',
    revealMessage: 'У Уст воздух густой от невысказанных исповедей — произнеси формулу.',
    completeMessage:
      'Формула принята. Первый акт еретика закрыт — Синод ответит силой, не словом.',
    completeWhen: { kind: 'finale', sceneId: ACT1_FINALE_SCENES.heretic },
    boostSceneId: ACT1_FINALE_SCENES.heretic,
    revealAfterStepId: 'h_main_4',
    reward: { echo: 5, journalEntries: ['act1_heretic'] },
  },
  {
    id: 'h_opt_cog',
    origin: 'heretic',
    type: 'optional',
    order: 10,
    titleHidden: 'Шестерня',
    titleRevealed: 'Встреча с шестерней',
    hint: 'Найти еретическую шестерню в глубине.',
    revealMessage: 'Железо без оси крутится в воздухе — вопрос без ответа Синода.',
    completeMessage:
      'Шестерня запомнила твой голос. У Порога Распада откроется иной путь.',
    completeWhen: { kind: 'scene', sceneId: 'act1_heretic_opt_cog' },
    boostSceneId: 'act1_heretic_opt_cog',
    revealAfterStepId: 'h_main_2',
    reward: { flags: ['met_heretic_cog'], journalEntries: ['npc_heretic'] },
  },
  {
    id: 'h_opt_depth',
    origin: 'heretic',
    type: 'optional',
    order: 11,
    titleHidden: 'Глубина',
    titleRevealed: 'Третий ярус',
    hint: 'Дойти до глубины 3 и услышать эхо формулы.',
    revealMessage: 'На третьем ярусе формулы звучат громче молитв.',
    completeMessage:
      'Глубина 3 принята. Стены помнят твой вопрос — не твоё имя.',
    completeWhen: { kind: 'scene', sceneId: 'act1_heretic_opt_depth' },
    boostSceneId: 'act1_heretic_opt_depth',
    scenePrerequisites: [{ kind: 'best_depth', min: 3 }],
    revealAfterStepId: 'h_main_3',
    reward: { echo: 3, materials: { iron_shard: 1 } },
  },
  {
    id: 'h_opt_twice',
    origin: 'heretic',
    type: 'optional',
    order: 12,
    titleHidden: 'Дважды',
    titleRevealed: 'Дважды живым',
    hint: 'Два успешных извлечения — хронист запишет.',
    revealMessage: 'Двойной возврат — редкая валюта у Машины.',
    completeMessage:
      'Два живых круга. Машина вычла из петли два вдоха — тебе оставила эхо.',
    completeWhen: { kind: 'scene', sceneId: 'act1_heretic_opt_twice' },
    boostSceneId: 'act1_heretic_opt_twice',
    scenePrerequisites: [{ kind: 'extractions', min: 2 }],
    revealAfterStepId: 'h_main_1',
    reward: { echo: 4 },
  },

  // ——— Пустой ———
  {
    id: 'o_main_1',
    origin: 'hollow',
    type: 'main',
    order: 1,
    titleHidden: '???',
    titleRevealed: 'Пустая форма',
    hint: 'Вернуться, чтобы камера узнала силуэт.',
    revealMessage:
      'Камера отпустила тебя — теперь она должна узнать форму, которой нет имени.',
    completeMessage:
      'Часовня без лиц приняла твой силуэт. Пустота здесь — не проклятие, а признание.',
    completeWhen: { kind: 'scene', sceneId: 'act1_hollow_empty_chapel' },
    boostSceneId: 'act1_hollow_empty_chapel',
    scenePrerequisites: [{ kind: 'extractions', min: 1 }],
    reward: { echo: 1 },
  },
  {
    id: 'o_main_2',
    origin: 'hollow',
    type: 'main',
    order: 2,
    titleHidden: '???',
    titleRevealed: 'Долг без имени',
    hint: 'Бездыханный ведёт счёт даже пустым.',
    revealMessage: 'У пустых тоже есть долг — минус одно имя, плюс одна маска.',
    completeMessage:
      'Бездыханный записал пустоту в счёт. Синод любит, когда отсутствие хоть чем-то звенит.',
    completeWhen: { kind: 'scene', sceneId: 'act1_hollow_merchant_debt' },
    boostSceneId: 'act1_hollow_merchant_debt',
    revealAfterStepId: 'o_main_1',
    reward: { materials: { wax_seal: 1 } },
  },
  {
    id: 'o_main_3',
    origin: 'hollow',
    type: 'main',
    order: 3,
    titleHidden: '???',
    titleRevealed: 'Маска в руке',
    hint: 'Взять то, что скрывает отсутствие лица.',
    revealMessage: 'Маска тяжелее пустой керамики — обряд без лица ждёт.',
    completeMessage:
      'Маска на поясе. Тело и отсутствие наконец совпали — голод под доспехами стих.',
    completeWhen: { kind: 'scene', sceneId: 'act1_hollow_mask_rite' },
    boostSceneId: 'act1_hollow_mask_rite',
    revealAfterStepId: 'o_main_2',
    reward: { materials: { choir_splinter: 1 }, flags: ['claimed_mask'] },
  },
  {
    id: 'o_main_4',
    origin: 'hollow',
    type: 'main',
    order: 4,
    titleHidden: '???',
    titleRevealed: 'Принять обвал',
    hint: 'Упасть и вернуться — не сбой, а урок.',
    revealMessage:
      'Камера помнит падение. Пустота не спасает от гравитации долга — прими урок.',
    completeMessage:
      'Обвал принят. Машина вытянула сосуд и оставила пятно — теперь это карта, не клеймо.',
    completeWhen: { kind: 'scene', sceneId: 'act1_hollow_collapse_lesson' },
    boostSceneId: 'act1_hollow_collapse_lesson',
    scenePrerequisites: [{ kind: 'flag', flag: 'experienced_failure' }],
    revealAfterStepId: 'o_main_3',
    reward: { echo: 3 },
  },
  {
    id: 'o_main_5',
    origin: 'hollow',
    type: 'main',
    order: 5,
    titleHidden: '???',
    titleRevealed: 'Имя, которого нет',
    hint: 'Финал: камера спрашивает то, чего у тебя нет.',
    revealMessage: 'У Рта спрашивают имя — у тебя есть только честная пустота.',
    completeMessage:
      'Записано: отсутствие. Первый акт пустого закрыт — камера знает форму без имени.',
    completeWhen: { kind: 'finale', sceneId: ACT1_FINALE_SCENES.hollow },
    boostSceneId: ACT1_FINALE_SCENES.hollow,
    revealAfterStepId: 'o_main_4',
    reward: { echo: 5, journalEntries: ['act1_hollow'] },
  },
  {
    id: 'o_opt_bell',
    origin: 'hollow',
    type: 'optional',
    order: 10,
    titleHidden: 'Колокол',
    titleRevealed: 'Звон без эха',
    hint: 'Услышать колокол у старца пустоты.',
    revealMessage: 'Колокол бьёт — но эха нет. Только пустой ветер отвечает.',
    completeMessage:
      'Звон прошёл сквозь тебя, не зацепившись. Старец пустоты кивнул: «Так и должно быть.»',
    completeWhen: { kind: 'scene', sceneId: 'act1_hollow_opt_bell' },
    boostSceneId: 'act1_hollow_opt_bell',
    revealAfterStepId: 'o_main_2',
    reward: { flags: ['heard_the_bell'], journalEntries: ['act1_opt_bell'] },
  },
  {
    id: 'o_opt_wax',
    origin: 'hollow',
    type: 'optional',
    order: 11,
    titleHidden: 'Воск',
    titleRevealed: 'Восковой паломник',
    hint: 'Встретить воскового — пустота считается иначе.',
    revealMessage: 'Паломник досчитывает пульс. У пустого его нет — только ритм камеры.',
    completeMessage:
      'Восковой записал пустоту как «ноль». Журнал принял — лица без пульса тоже существуют.',
    completeWhen: { kind: 'scene', sceneId: 'act1_hollow_opt_wax' },
    boostSceneId: 'act1_hollow_opt_wax',
    revealAfterStepId: 'o_main_2',
    reward: { materials: { wax_seal: 2 }, journalEntries: ['npc_wax'] },
  },
  {
    id: 'o_opt_twice',
    origin: 'hollow',
    type: 'optional',
    order: 12,
    titleHidden: 'Дважды',
    titleRevealed: 'Дважды живым',
    hint: 'Два извлечения — хронист вырежет второй силуэт.',
    revealMessage: 'Два возврата без имени — редкость. Камера вырежет силуэт глубже.',
    completeMessage:
      'Второй силуэт на стене чётче первого. Пустота дважды доказала, что форма держится.',
    completeWhen: { kind: 'scene', sceneId: 'act1_hollow_opt_twice' },
    boostSceneId: 'act1_hollow_opt_twice',
    scenePrerequisites: [{ kind: 'extractions', min: 2 }],
    revealAfterStepId: 'o_main_1',
    reward: { echo: 4 },
  },

  // ——— Свидетель: дополнительные опциональные ———
  {
    id: 'w_opt_choir',
    origin: 'witness',
    type: 'optional',
    order: 13,
    titleHidden: 'Хор',
    titleRevealed: 'Третий голос',
    hint: 'В Расколотом нефе слушать голос, который не левый и не правый.',
    revealMessage:
      'Свидетель смотрит — и это тоже нота. Хор ждёт взгляд, не молитву.',
    completeMessage:
      'Третий голос принял твой взгляд. Погребённый хор запомнил свидетеля — не как певца, как **смотрящего**.',
    completeWhen: { kind: 'scene', sceneId: 'act1_witness_opt_choir' },
    boostSceneId: 'act1_witness_opt_choir',
    revealAfterStepId: 'w_main_3',
    reward: { echo: 2, flags: ['choir_witness'] },
  },
  {
    id: 'w_opt_mirror',
    origin: 'witness',
    type: 'optional',
    order: 14,
    titleHidden: 'Зеркало',
    titleRevealed: 'Зеркальная запись',
    hint: 'В парлоре шёпотов принять отражение долга.',
    revealMessage:
      'Зеркало не показывает лицо — показывает того, кого ты видел. Запиши, пока Синод не стёр.',
    completeMessage:
      'Отражение принято. Синод назовёт это ересью учёта — камера запомнит честнее.',
    completeWhen: { kind: 'scene', sceneId: 'act1_witness_opt_mirror' },
    boostSceneId: 'act1_witness_opt_mirror',
    revealAfterStepId: 'w_main_2',
    reward: { journalEntries: ['act1_witness_mirror'] },
  },
  {
    id: 'w_opt_herald',
    origin: 'witness',
    type: 'optional',
    order: 15,
    titleHidden: 'Обочина',
    titleRevealed: 'Вестник Шествия',
    hint: 'Встретить паломника с обочины — не из строя.',
    revealMessage:
      'Шествие ушло в трещину. Обочина помнит тех, кто смотрел, но не пошёл.',
    completeMessage:
      'Вестник записал разницу между шагом и взглядом. Долг свидетеля стал **точнее**.',
    completeWhen: { kind: 'scene', sceneId: 'encounter_procession_herald' },
    boostSceneId: 'encounter_procession_herald',
    revealAfterStepId: 'w_main_1',
    reward: { materials: { wax_seal: 1 }, journalEntries: ['npc_procession'] },
  },
  {
    id: 'w_opt_raids',
    origin: 'witness',
    type: 'optional',
    order: 16,
    titleHidden: 'Трижды',
    titleRevealed: 'Три круга',
    hint: 'Три спуска и запись хрониста о живых возвратах.',
    revealMessage:
      'Три насечки на стене камеры — редкость для свидетеля, который не только смотрит, но и **возвращается**.',
    completeMessage:
      'Треугольник пепла замкнут. Машина приняла третий круг как доказательство, не упрямство.',
    completeWhen: {
      kind: 'all',
      conditions: [
        { kind: 'scene', sceneId: 'act1_witness_opt_raids' },
        { kind: 'raids', min: 3 },
      ],
    },
    boostSceneId: 'act1_witness_opt_raids',
    scenePrerequisites: [{ kind: 'raids', min: 3 }],
    revealAfterStepId: 'w_main_2',
    reward: { echo: 3 },
  },
  {
    id: 'w_opt_iron',
    origin: 'witness',
    type: 'optional',
    order: 17,
    titleHidden: 'Железо',
    titleRevealed: 'Железный хранитель',
    hint: 'На третьем ярусе записать чужое имя в железную книгу.',
    revealMessage:
      'Металл помнит имена — не голоса. Свидетель обязан дописать учёт на глубине.',
    completeMessage:
      'Железный хранитель принял строку. Глубина знает свидетеля — Синод допишет позже.',
    completeWhen: { kind: 'scene', sceneId: 'encounter_iron_keeper' },
    boostSceneId: 'encounter_iron_keeper',
    scenePrerequisites: [{ kind: 'best_depth', min: 3 }],
    revealAfterStepId: 'w_main_4',
    reward: { materials: { iron_shard: 2 }, echo: 1 },
  },

  // ——— Еретик: дополнительные опциональные ———
  {
    id: 'h_opt_mirror',
    origin: 'heretic',
    type: 'optional',
    order: 13,
    titleHidden: 'Отражение',
    titleRevealed: 'Формула в зеркале',
    hint: 'Переписать стёртую строку из отражения.',
    revealMessage:
      'Синод стирает стены — зеркало помнит. Еретик переписывает, не молится.',
    completeMessage:
      'Формула в отражении принята. Катакомбы получат строку, которую Синод не услышит.',
    completeWhen: { kind: 'scene', sceneId: 'act1_heretic_opt_mirror' },
    boostSceneId: 'act1_heretic_opt_mirror',
    revealAfterStepId: 'h_main_3',
    reward: { materials: { folio_page: 1 }, flags: ['read_the_writings'] },
  },
  {
    id: 'h_opt_choir',
    origin: 'heretic',
    type: 'optional',
    order: 14,
    titleHidden: 'Гимн',
    titleRevealed: 'Петь без Синода',
    hint: 'Произнести формулу в такт Погребённому хору.',
    revealMessage:
      'Третий голос считает, не поёт. Еретик должен **допеть** формулу в нефе.',
    completeMessage:
      'Гимн сбился — Машина записала. Синод отстаёт на полтона.',
    completeWhen: { kind: 'scene', sceneId: 'act1_heretic_opt_choir' },
    boostSceneId: 'act1_heretic_opt_choir',
    revealAfterStepId: 'h_main_3',
    reward: { echo: 2, flags: ['choir_heretic'] },
  },
  {
    id: 'h_opt_ash',
    origin: 'heretic',
    type: 'optional',
    order: 15,
    titleHidden: 'Пепел',
    titleRevealed: 'Пепельница',
    hint: 'Встретить ту, кто шьёт обрывки памяти камеры.',
    revealMessage:
      'Память рвётся между спусками. Пепельница шьёт — не для Синода.',
    completeMessage:
      'Шов принят. Обрывок прошлого спуска снова держит форму — ценой формулы.',
    completeWhen: { kind: 'scene', sceneId: 'encounter_ash_weaver' },
    boostSceneId: 'encounter_ash_weaver',
    revealAfterStepId: 'h_main_2',
    reward: { materials: { wax_seal: 2 }, journalEntries: ['npc_ash_weaver'] },
  },
  {
    id: 'h_opt_memory',
    origin: 'heretic',
    type: 'optional',
    order: 16,
    titleHidden: 'Обмен',
    titleRevealed: 'Память за слух',
    hint: 'Отдать Бездыханному обрывок памяти — принять слух.',
    revealMessage:
      'Телега помнит еретиков. Бездыханный торгует слухами, которые Синод не купит.',
    completeMessage:
      'Память ушла — формула пришла. Счёт телеги и камеры снова не совпадают.',
    completeWhen: { kind: 'scene', sceneId: 'act1_heretic_opt_memory' },
    boostSceneId: 'act1_heretic_opt_memory',
    scenePrerequisites: [{ kind: 'flag', flag: 'met_breathless' }],
    revealAfterStepId: 'h_main_2',
    reward: { echo: 3, flags: ['merchant_memory_trade'] },
  },
  {
    id: 'h_opt_vein',
    origin: 'heretic',
    type: 'optional',
    order: 17,
    titleHidden: 'Жила',
    titleRevealed: 'Пророк жилы',
    hint: 'На четвёртом ярусе услышать то, что дышит внутрь.',
    revealMessage:
      'Уста дышат не вниз — внутрь. Жила спросит, что останется после формулы.',
    completeMessage:
      'Жила ответила. Еретик знает цену точности на Пороге Распада.',
    completeWhen: { kind: 'scene', sceneId: 'encounter_vein_prophet' },
    boostSceneId: 'encounter_vein_prophet',
    scenePrerequisites: [{ kind: 'best_depth', min: 4 }],
    revealAfterStepId: 'h_main_4',
    reward: { echo: 4, journalEntries: ['npc_vein_prophet'] },
  },

  // ——— Пустой: дополнительные опциональные ———
  {
    id: 'o_opt_mirror_nun',
    origin: 'hollow',
    type: 'optional',
    order: 13,
    titleHidden: 'Зеркало',
    titleRevealed: 'Монахиня зеркала',
    hint: 'В монастыре Полых Святых принять форму без лица.',
    revealMessage:
      'Они вырезали лишнее. Пустой родился лишним — зеркало это **понимает**.',
    completeMessage:
      'Монахиня кивнула в бронзе. Форма без имени — не ошибка, а **обряд**.',
    completeWhen: { kind: 'scene', sceneId: 'encounter_mirror_nun' },
    boostSceneId: 'encounter_mirror_nun',
    revealAfterStepId: 'o_main_2',
    reward: { journalEntries: ['npc_mirror_nun'], flags: ['mirror_nun_met'] },
  },
  {
    id: 'o_opt_chapel',
    origin: 'hollow',
    type: 'optional',
    order: 14,
    titleHidden: 'Часовня',
    titleRevealed: 'Второй визит',
    hint: 'Вернуться в часовню без имён второй раз.',
    revealMessage:
      'Часовня помнит силуэт лучше камеры. Второй визит — плотнее первого.',
    completeMessage:
      'Стены приняли форму снова. Пустота здесь — признание, не проклятие.',
    completeWhen: { kind: 'scene', sceneId: 'act1_hollow_opt_chapel_return' },
    boostSceneId: 'act1_hollow_opt_chapel_return',
    scenePrerequisites: [{ kind: 'extractions', min: 2 }],
    revealAfterStepId: 'o_main_1',
    reward: { echo: 2 },
  },
  {
    id: 'o_opt_mask_trade',
    origin: 'hollow',
    type: 'optional',
    order: 15,
    titleHidden: 'Весы',
    titleRevealed: 'Маска на вес',
    hint: 'Отвесить маску у Бездыханного — или унести к Устам.',
    revealMessage:
      'Синод ведёт учёт маской. Пустой должен решить: товар или **честь**.',
    completeMessage:
      'Счёт записан. Отсутствие звенит — как Синод и хотел.',
    completeWhen: { kind: 'scene', sceneId: 'act1_hollow_opt_mask_trade' },
    boostSceneId: 'act1_hollow_opt_mask_trade',
    scenePrerequisites: [{ kind: 'flag', flag: 'claimed_mask' }],
    revealAfterStepId: 'o_main_3',
    reward: { materials: { choir_splinter: 1 }, flags: ['mask_traded'] },
  },
  {
    id: 'o_opt_ash_path',
    origin: 'hollow',
    type: 'optional',
    order: 16,
    titleHidden: 'Тропа',
    titleRevealed: 'Пепельная тропа',
    hint: 'Идти боком, туда, где Шествие не считает.',
    revealMessage:
      'Синод не ходит боком. Пепельная тропа — для тех, у кого нет имени в книге.',
    completeMessage:
      'Тропа приняла пустоту. Колокол ударил — эха не было. Так и должно быть.',
    completeWhen: { kind: 'scene', sceneId: 'act1_hollow_opt_ash_path' },
    boostSceneId: 'act1_hollow_opt_ash_path',
    revealAfterStepId: 'o_main_3',
    reward: { echo: 3, flags: ['ash_path_walked'] },
  },
  {
    id: 'o_opt_iron',
    origin: 'hollow',
    type: 'optional',
    order: 17,
    titleHidden: 'Ноль',
    titleRevealed: 'Железный ноль',
    hint: 'Записать ноль в железную книгу на глубине.',
    revealMessage:
      'Железный хранитель ждёт строку. У пустого — **ноль**, не имя.',
    completeMessage:
      'Ноль записан. Металл принял отсутствие как честную строку учёта.',
    completeWhen: { kind: 'scene', sceneId: 'encounter_iron_keeper' },
    boostSceneId: 'encounter_iron_keeper',
    scenePrerequisites: [{ kind: 'best_depth', min: 3 }],
    revealAfterStepId: 'o_main_4',
    reward: { materials: { iron_shard: 1 }, echo: 2 },
  },
]

export function stepsForOrigin(origin: string): ActQuestStepDef[] {
  return ACT1_QUEST_STEPS.filter((s) => s.origin === origin).sort(
    (a, b) => a.order - b.order,
  )
}
